#!/bin/sh

# chkconfig:   - 85 15
# description:  ocserv is a cisco anyconnect server
# processname: ocserv
# config:      /etc/ocserv/ocserv.conf
# pidfile:     /var/run/ocserv.pid



LD_LIBRARY_PATH=/opt/lib/:/opt/lib64/
export PATH=$PATH:/opt/bin


DAEMON_ARGS="-c /etc/ocserv/ocserv.conf"
OCCTL=/opt/bin/occtl

ocserv="/opt/bin/ocserv"
prog=$(basename $ocserv)

lockfile=/var/lock/subsys/ocserv


start() {
    [ -x $ocserv ] || exit 5
    echo -n $"Starting $prog: "
    daemon $ocserv $DAEMON_ARGS
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -QUIT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}



case "$1" in
    start)
        $1
        ;;
    stop)
       
        $1
        ;;
    restart)
        $1
        ;;


    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

